#!/bin/bash

export DATA_SOURCE_NAME=$(./data_source)

./mysqld_exporter                               \
  --web.listen-address=":$PORT"                 \
  --collect.auto_increment.columns=true         \
  --collect.binlog_size=true                    \
  --collect.info_schema.clientstats=true        \
  --collect.info_schema.processlist=true        \
  --collect.info_schema.tables.databases='*'    \
  --collect.info_schema.tablestats=true         \
  --collect.info_schema.userstats=true          \
  --collect.slave_status=false
