#!/bin/bash

wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.10.0/mysqld_exporter-0.10.0.linux-amd64.tar.gz
tar xvfz mysqld_exporter-0.10.0.linux-amd64.tar.gz
mv mysqld_exporter-0.10.0.linux-amd64/mysqld_exporter mysqld_exporter
rm -r mysqld_exporter-0.10.0.linux-amd64
rm mysqld_exporter-0.10.0.linux-amd64.tar.gz
